### ISSUE TITLE
include error when using in platformio

### ISSUE THREAD

**Issue by ProjectPatatoe** [embeddedartistry/arduino-printf#17]
When using inside of PlatformIO I get this error about dependency.

```
cannot open source file "../extras/printf/printf.h" (dependency of "LibPrintf.h")C/C++(1696)
```
```
.pio\libdeps\nanoatmega328new\LibPrintf\src\LibPrintf.h:5:37: fatal error: ../extras/printf/printf.h: No such file or directory
```

**Comment by phillipjohnston** [comment]
Hello,

I’ve never used PlatformIO, so I can’t provide a helpful answer at the moment. 

I’m curious: do those files actually exist wherever the Arduino-printf files are kept?

**Comment by studionebula** [comment]
I don't know how PlatformIO interfaces to github, but the problem appears to be that when PlatformIO pulls the library into the project, it does not grab the extras folder. Thus the compilation fails because the header file can't be found, as the original poster described. Sorry that I can't tell you how to fix it; this kind of seems like PlatformIO's issue rather than yours.
The workaround, obviously, is to download the library from here and copy its extras folder into the LibPrintf folder, which is at .pio/libdeps/<configuration_name>/LibPrintf .

**Comment by EmperorArthur** [comment]
There is a work around!

Instead of relying on platformio's own (faulty) packages, just use the github archive directly.

Put this in your platformio.ini file:
```
lib_deps = 
	LibPrintf=https://github.com/embeddedartistry/arduino-printf/archive/1.1.4.tar.gz
```

**Comment by uchnz** [comment]
> 

worked for me. Thanks!
